#!/bin/bash -x

env

goVersion="1.10"
goLDFlags"=-ldflags \"-X main.gitCommit=${SOURCE_COMMIT} -X main.productVersion=0.1 -X main.goVersion=go${goVersion}\""

cd ../../..
mkdir _output
docker run --rm -v "$PWD":/go/src/github.com/oracle/speedle -v "$PWD/_output":/go/bin golang:${goVersion} go build ${goLDFlags} -o /go/bin/speedle-pms github.com/oracle/speedle/cmd/speedle-pms

